# Generated by Django 4.1.6 on 2023-02-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transation_state',
            field=models.BooleanField(default=False, help_text='Approve deposit transacttion transaction here'),
        ),
    ]
