# Generated by Django 4.1.6 on 2023-02-25 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_transation_state_transaction_transaction_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminwalletaccount',
            name='bank_account_name',
        ),
        migrations.RemoveField(
            model_name='adminwalletaccount',
            name='bank_account_number',
        ),
        migrations.RemoveField(
            model_name='adminwalletaccount',
            name='bank_name',
        ),
    ]
