# Generated by Django 4.1.6 on 2023-02-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_adminwalletaccount_bank_account_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, verbose_name='Client Email')),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
